version: '2'
services:
  api:
    build:
      context: .
    command: sh -c "gunicorn -w 4 -b 0.0.0.0:5000 --reload 'cashback.api.run:create_app()'"
    environment:
      - PORT=5000
    depends_on:
      - db
    ports:
      - "5000:5000"

  db:
    image: postgres:11
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - DATABASE_URL=postgresql://postgres:postgres@db/postgres

# python -m src.database.generate_db && 