version: '2'
services:
  api:
    build:
      context: .
    command: sh -c "python -m scripts.create_postgresql_db && gunicorn -w 4 -b 0.0.0.0:5000 --reload 'cashback.api.run:create_app()'"
    environment:
      - POSTGRESQL_URI=postgresql://postgres:postgres@db/postgres
    depends_on:
      - db
    ports:
      - "5000:5000"

  mock_api:
    build:
      context: .
    command: sh -c "python -m scripts.create_postgresql_db && python -m mock_workers.api"
    restart: always
    environment:
      - POSTGRESQL_URI=postgresql://postgres:postgres@db/postgres
    depends_on:
      - db
    ports:
      - "5001:5001"

  mock_consumer:
    build:
      context: .
    command: sh -c "python -m mock_workers.consumer"
    restart: always
    stdin_open: true
    tty: true
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=guest
      - RABBITMQ_PASS=guest
      - POSTGRESQL_URI=postgresql://postgres:postgres@db/postgres
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3.10.7-alpine
    restart: always
    ports:
      - "5672:5672"

  db:
    image: postgres:11
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - DATABASE_URL=postgresql://postgres:postgres@db/postgres
